# Generated by Django 4.1.7 on 2023-03-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0002_coachauth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coach',
            old_name='panchayath',
            new_name='village',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='photo',
        ),
        migrations.AddField(
            model_name='coach',
            name='state',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
