# Generated by Django 4.1.7 on 2023-04-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0004_coach_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='contact',
            field=models.IntegerField(default=0),
        ),
    ]
