# Generated by Django 4.1.7 on 2023-04-05 05:00

import coach.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0008_remove_coach_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='contact',
            field=models.IntegerField(default=coach.models.get_default_value),
        ),
    ]
