# Generated by Django 4.1.7 on 2023-04-05 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_match_remove_match_details_match_remove_staff_photo_and_more'),
        ('coach', '0009_coach_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='match',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
