# Generated by Django 4.1.7 on 2023-04-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0013_remove_coach_userid_coach_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
