# Generated by Django 4.1.6 on 2023-05-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0015_alter_attendance_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='team_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
    ]
