# Generated by Django 4.1.7 on 2023-03-21 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0001_initial'),
        ('coach', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('photo', models.FileField(upload_to=None)),
                ('housename', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('panchayath', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_matches', models.IntegerField(default=50)),
                ('goals', models.IntegerField(default=50)),
                ('assists', models.IntegerField(default=50)),
                ('cleansheets', models.IntegerField(default=50)),
                ('red_cards', models.IntegerField(default=50)),
                ('yellow_cards', models.IntegerField(default=50)),
                ('pname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.player')),
            ],
        ),
        migrations.CreateModel(
            name='match_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_scored', models.IntegerField(default=50)),
                ('goal_owned', models.IntegerField(default=50)),
                ('Match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coach.match')),
            ],
        ),
    ]
