# Generated by Django 4.1.7 on 2023-04-05 05:06

from django.db import migrations, models
import staff.models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staffauth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opposite_team', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='match_details',
            name='Match',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='photo',
        ),
        migrations.AddField(
            model_name='staff',
            name='contact',
            field=models.IntegerField(default=staff.models.get_default_value),
        ),
    ]
