# Generated by Django 4.1.7 on 2023-04-05 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_delete_match_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='match_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_scored', models.IntegerField(default=50)),
                ('goal_owned', models.IntegerField(default=50)),
                ('Match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.match')),
            ],
        ),
    ]
