# Generated by Django 4.1.7 on 2023-04-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_match_details_status_alter_performance_assists_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match_details',
            name='goal_owned',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='match_details',
            name='goal_scored',
            field=models.IntegerField(),
        ),
    ]
