# Generated by Django 4.1.6 on 2023-05-14 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0018_rename_statictics_team_type'),
        ('staff', '0008_alter_match_details_goal_owned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match_details',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coach.team_type'),
        ),
    ]
