# Generated by Django 4.1.7 on 2023-04-03 07:06

from django.db import migrations, models
import player.models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_playerauth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='panchayath',
        ),
        migrations.RemoveField(
            model_name='player',
            name='photo',
        ),
        migrations.AddField(
            model_name='player',
            name='state',
            field=models.CharField(default=player.models.get_default_value, max_length=50),
        ),
        migrations.AddField(
            model_name='player',
            name='thaluk',
            field=models.CharField(default=player.models.get_default_value, max_length=50),
        ),
        migrations.AddField(
            model_name='player',
            name='village',
            field=models.CharField(default=player.models.get_default_value, max_length=50),
        ),
    ]
