# Generated by Django 4.1.7 on 2023-04-03 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_remove_player_panchayath_remove_player_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='post',
        ),
    ]
