# Generated by Django 4.1.7 on 2023-04-05 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_remove_player_thaluk'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
