# Generated by Django 4.1.7 on 2023-04-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_player_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='coach',
            field=models.IntegerField(default=0),
        ),
    ]
