# Generated by Django 4.1.7 on 2023-03-27 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_managerauth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='managerauth',
        ),
    ]
