# Generated by Django 4.1.7 on 2023-03-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_cuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='stfuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
