# Generated by Django 4.1.7 on 2023-04-05 05:00

from django.db import migrations, models
import manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_login_delete_cuser_delete_stfuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='contact',
            field=models.IntegerField(default=manager.models.get_default_value),
        ),
    ]
