# Generated by Django 4.1.7 on 2023-04-13 06:39

from django.db import migrations, models
import django.db.models.deletion
import manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_manager_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='mname',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='panchayath',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='photo',
        ),
        migrations.AddField(
            model_name='manager',
            name='login',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.login'),
        ),
        migrations.AddField(
            model_name='manager',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='village',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='contact',
            field=models.IntegerField(default=manager.models.get_default_value, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='district',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='housename',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='place',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='post',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
